server:
  port: 5000
  tomcat:
    max-http-form-post-size: 20MB

logging:
  file:
    name: ./logs/service.log
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/srv27_antoshka?currentSchema=front
    username: antoshkauser
    password: antoshkapass
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
